---
- include_tasks: ./linux-amazon-software-installation.yml

- name: Instalar software esencial en Amazon 2
  package:
    name: "{{ linux_amazon2_packages }}"
    state: present
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"
