---
- name: Update package cache repository from OS (RedHat)
  when:
    - os_vendor == "rhel" or os_vendor == "oracle" or os_vendor == "centos" or os_vendor == "rocky"
  command:
    cmd: "yum makecache"
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"
  register: check_yum

- name: Update package cache (Zypper only)
  when: os_vendor == "sles"
  command:
    cmd: "zypper refresh"
    warn: false
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"
  register: check_zypper

- name: Update package cache (Debian Family only)
  when: os_vendor == "ubuntu" or os_vendor == "debian" or os_vendor == "kali"
  command:
    cmd: "apt update"
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"
  register: check_apt

- when:
    - check_apt.rc is defined
  set_fact:
    install_pkg: "{{ true if check_apt.rc == 0 else false }}"

- when:
    - check_yum.rc is defined
  set_fact:
    install_pkg: "{{ true if check_yum.rc == 0 else false }}"

- when:
    - check_zypper.rc is defined
  set_fact:
    install_pkg: "{{ true if check_zypper.rc == 0 else false }}"

- when:
    - install_pkg == true
  block:
    - name: include prerequisites to SO new
      include_tasks: linux-prerequisites.yml
      ignore_errors: true

    - name: Install generic package in redhat/debian/sles
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ linux_generic_all_packages }}"
      environment:
        http_proxy: "{{ proxy | default(omit) }}"
        https_proxy: "{{ proxy | default(omit) }}"

    - name: Instalar software de Red Hat/CentOS
      include_tasks: linux-redhat-software-installation.yml
      when: (os_vendor == 'centos' or
        os_vendor == 'rhel' or
        os_vendor == 'oracle' or
        os_vendor == 'rocky')

    - name: Instalar software de Debian/Ubuntu
      include_tasks: linux-debian-software-installation.yml
      when: os_vendor == 'ubuntu' or
        os_vendor == 'debian'

    - name: Instalar software de SUSE
      include_tasks: linux-suse-software-installation.yml
      when: os_vendor == 'sles'

    - name: Instalar software de Amazon
      include_tasks: linux-amazon-software-installation.yml
      when: (os_vendor == 'amazon' and os_release != '2')

    - name: Instalar software de Amazon 2
      include_tasks: linux-amazon2-software-installation.yml
      when: (os_vendor == 'amazon' and os_release == '2')

    - name: Habilitar servicio atd
      service:
        name: atd
        state: started
        enabled: yes

- name: Configurar SSH - Deshabilitar consultas DNS
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^UseDNS"
    line: "UseDNS no"

- name: Configurar SSH - Ajustes de keepalive 1
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^ClientAliveInterval"
    line: "ClientAliveInterval 30"

- name: "change password authentication of no/yes"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication(.*)no"
    line: "PasswordAuthentication yes"

- name: Configurar SSH - Ajustes de keepalive 2
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^ClientAliveCountMax"
    line: "ClientAliveCountMax 5"
  notify:
    - restart sshd

- name: Deshabilitar SELinux|
  selinux:
    state: disabled
  when: os_vendor == 'centos' or
    os_vendor == 'oracle' or
    os_vendor == 'rhel' or
    os_vendor == 'rocky' or
    (os_vendor == 'amazon' and
    os_release == '2') and
    selinux_disabled == true

- name: Personalizacion de parametros de kernel en RHEL/CentOS
  when: (os_vendor == 'centos' or
    os_vendor == 'rhel' or
    os_vendor == 'oracle' or
    os_vendor == 'rocky') and
    os_release.split('.')[0] == '7'
  block:
    - name: Remover parametros rhgb y quiet en RHEL/CentOS
      replace:
        path: /etc/default/grub
        regexp: "rhgb|quiet"
      register: edit_grub

    - name: Regenerar configuracion de grub
      shell: |
        grub2-mkconfig -o /boot/grub2/grub.cfg
      register: reconf_grub
      when: edit_grub.changed

- name: Configurar zona horaria a America/Lima
  timezone:
    name: America/Lima
