---
- name: Instalar software esencial en Debian/Ubuntu
  apt:
    name: "{{ linux_debian_packages }}"
    state: present
    update_cache: true
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"
