---
- name: install pkg generic epel for CentOS
  when: os_vendor == "centos" or os_vendor == "oracle" or os_vendor == "rocky"
  include_tasks:
    file: linux-redhat-software-epel.yml

- name: install packages generic to rhel
  package:
    name: "{{item}}"
    state: present
  loop: "{{ linux_generic_rhel_packages }}"
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"

- name: Instalar software esencial en Redhat/Centos/Oracle < 6
  yum:
    name: "{{ linux_redhat6_packages }}"
    state: present
  when: os_release.split('.')[0] == '6'
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"

- name: Instalar software esencial en Red Hat/CentOS/Oracle = 7
  yum:
    name: "{{ linux_redhat7_packages }}"
    state: present
  when: os_release.split('.')[0] == '7'
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"

- name: Instalar software esencial en CentOS/RHEL/Oracle High Version = 8
  yum:
    name: "{{ linux_redhat8_packages }}"
    state: present
  when: os_release.split('.')[0] == '8'
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"

- name: Instalar software esencial en CentOS/RHEL/Oracle High Version = 9
  yum:
    name: "{{ linux_redhat9_packages }}"
    state: present
  when: os_release.split('.')[0] == '9'
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"

- name: Instalar Server with GUI en RHEL 8-9 / CentOS 8-9 / Oracle 8-9
  shell: |
    dnf groupinstall -y --skip-broken "Server with GUI"
  when:
    - os_release.split('.')[0] >= '8'
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"

- name: Remover software innecesario
  yum:
    name: libvirt-daemon
    state: absent
  environment:
    http_proxy: "{{ proxy | default(omit) }}"
    https_proxy: "{{ proxy | default(omit) }}"
