---
- hosts: all
  become: true
  gather_facts: true
  vars:
    disabled: false
    remove_ip: ""
    ip_proxy: "127.0.0.1:3128"
    install_pkg: True
    client: ""
  tasks:

    - name: Define global vars
      set_fact:
            proxy_env:
              http_proxy: "{{  ip_proxy | default(omit) }}"
              https_proxy: "{{  ip_proxy | default(omit) }}"
              ftp_proxy: "{{  ip_proxy | default(omit) }}"

    - include_role:
        name: ansible_os_basevars

    - name: up values for subscription
      include_tasks: password.yml

    - include_role:
        name: ansible_os_register
      vars:
        os_register_state: present
