---
- name: "Cambiar nombres y usuarios"
  hosts: all
  become: true
  gather_facts: true
  tasks:

     - name: Change password user
       ansible.builtin.user:
          name: "{{ item.name }}"
          password: "{{ item.password }}"
       loop: users

     - name: Copy the file authorized_keys
       ansible.builtin.copy:
          src: ./eflores.pub
          dest: /home/"{{ item.name }}/authorized_keys"
          owner: "{{ item.name }}"
          group: "{{ item.group }}"
          mode: "0600"
