---
- hosts: all
  become: true
  gather_facts: true
  vars:
    client: ""
    selinux_disabled: true
    proxy: ""
    enable_satellite: false
    disabled: false
  tasks:
    - name: load values by default
      ansible.builtin.include_role:
        name: ansible_os_basevars

    - name: up values for subscription
      ansible.builtin.include_tasks: password.yml
      vars:
        client: ""

    - name: register the rhel/sles family
      ansible.builtin.include_role:
        name: ansible_os_register
      vars:
        os_register_state: present

    - name: personalice so vagrant with my users
      ansible.builtin.include_role:
        name: ansible_os_defaultvg

    - name: create users systems and generic
      ansible.builtin.include_role:
        name: ansible_os_users

    - name: configure base line
      ansible.builtin.include_role:
        name: ansible_os_baseline

    - name: configure tools to monitoring
      ansible.builtin.include_role:
        name: ansible_os_monitoring

    - name: Apply hardening to remote server
      ansible.builtin.include_role:
        name: ansible_os_hardening

    - name: Remove the license from remote server (Family RHEL/SLES) - desactived
      ansible.builtin.include_role:
        name: os_line_register_vagrant
      when: disabled == 'true'
      vars:
        os_register_state: absent
