---
- hosts: all
  become: true
  gather_facts: true
  vars:
    client: ""
    selinux_disabled: true
    proxy: ""
    enable_satellite: false
    disabled: false
  tasks:
    - name: load values by default
      include_role:
        name: ansible_os_basevars

    - name: up values for subscription
      include_tasks: password.yml
      vars:
        client: ""

    - name: register the rhel/sles family
      include_role:
        name: ansible_os_register
      vars:
        os_register_state: present

    - name: personalice so vagrant with my users
      include_role:
        name: ansible_os_defaultvg

    - name: create users systems and generic
      include_role:
        name: ansible_os_users

    - name: configure base line
      include_role:
        name: ansible_os_baseline

    - name: configure tools to monitoring
      include_role:
        name: ansible_os_monitoring

    - name: apply hardening to remote server
      include_role:
        name: ansible_os_hardening

    - include_role:
        name: os_line_register_vagrant
      when: disabled == 'true'
      vars:
        os_register_state: absent
