---
- hosts: all
  become: true
  gather_facts: true
  vars:
    disabled: false
    remove_ip: ""
    ip_proxy:
    install_pkg: True
    client: ""
  tasks:

    - name: Define global vars
      set_fact:
            proxy_env:
              http_proxy: "{{  ip_proxy | default(omit) }}"
              https_proxy: "{{  ip_proxy | default(omit) }}"
              ftp_proxy: "{{  ip_proxy | default(omit) }}"

    - include_role:
        name: ansible_os_basevars

    - include_role:
        name: ansible_os_register 
      when: disabled == 'true'
      vars:
        os_register_state: absent
