---
- name: test nginx configuration 
  ansible.builtin.command: nginx -t 
  listen: reload nginx 

- name: reload nginx service 
  service:
    name: nginx 
    state: reloaded 
  listen: reload nginx  
