---
- name: Nginx config 
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf 

- name: Nginx default config 
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  when: nginx_default_conf

- name: create conf to modules  
  file:
    path: "{{item}}"
    state: present 
    owner: nginx 
    group: nginx 
    mode: 644 
  loop: "{{nginx_modules}}"

- name: Sample content
  copy: 
    content: "Hello Nginx"
    dest: "{{ nginx_default_root }}/index.html"
  notify: reload nginx 

- name: Create working directory 
  file:
    path: "{{ nginx_default_root }}"
    state: directory 
