---
- name: install epel-release on Centos
  when: os_vendor == "centos"
  yum: 
    name: epel-release
    state: installed

- name: install epel-release on RedHat 
  when: os_vendor == "rhel"
  yum: 
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm'
    state: present 

