---
- name: Init block
  become: true
  block:

   - name: Link to program yaml-language-server
     ansible.builtin.file:
      src: "/home/{{ item }}/node_modules/yaml-language-server/bin/yaml-language-server"
      path: /usr/local/bin
      state: link
     loop: "{{ usuarios }}"

   - name: Link to program yaml-language-server
     ansible.builtin.file:
      src: "/home/{{ item }}/node_modules/tree-sitter-cli/tree-sitter"
      path: /usr/local/bin
      state: link
     loop: "{{ usuarios }}"
