---
- name: Pause for 2 minutes to build app cache
  ansible.builtin.pause:
    minutes: 2

- name: Install packages extras
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ base_packages }}"
    - "{{ packages }}"

- name: Update packages from local
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: true

- name: Install package extras
  ansible.builtin.include_tasks:
    file: get_temp_url.yml

- name: Install deb packages
  ansible.builtin.apt:
    deb: "{{ item.package }}"
    state: present
  loop: "{{ url_deb }}"

- name: Install binary script aws
  ansible.builtin.command: ./aws/install
  register: aws_install
  changed_when: aws_install.rc != 0
  args:
    chdir: /tmp/
    executable: /bin/bash
  ignore_errors: true

- name: Install discord new version
  ansible.builtin.apt:
    deb: /tmp/discord.deb
    state: present

- name: Install packages from snap
  community.general.snap:
    name: "{{ item }}"
    state: present
    classic: true
  loop: "{{ snap_packages }}"

- name: Download tarball in the /opt/
  ansible.builtin.unarchive:
    src: /tmp/thunderbird.tar.gz
    dest: /opt/
    remote_src: true
