---
    - name: remove package installed
      when: check_package.rc == 0
      yum: 
        name: "{{check_package.stdout_lines}}"
        state: absent

    - name: copy file installer to /usr/local/src/
      copy:
        src: files/{{file_installer}}.el{{ansible_distribution_major_version}}.{{ansible_machine}}.rpm
        dest: /usr/local/src/

    - name: install when redhat family
      block:
      - name: Install in {{ansible_distribution}} - {{ansible_distribution_major_version}}
        yum:
          name: /usr/local/src/{{file_installer}}.el{{ansible_distribution_major_version}}.{{ansible_machine}}.rpm
          state: present