---
- name: update package to system operating RedHat/Centos <= 7 
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 7
  yum: 
    name: '*'
    state: latest
    update_cache: true
  environment: "{{ proxy_env | default(omit)}}"

- name: update package to system operating RedHat/CentOS >=8
  when: 
    - ansible_os_family == "RedHat" and ( ansible_distribution_major_version|int == 8 or ansible_distribution_major_version|int == 9 )
  dnf:
    name: '*'
    state: latest 
    update_cache: true
  environment: "{{ proxy_env | default(omit)}}"

- name: update package to system operating Debian/Ubuntu 
  when: ansible_os_family == "Debian" 
  apt: 
    upgrade: full
    update_cache: true
    force_apt_get: true 
  environment: "{{ proxy_env | default(omit)}}"

- name: update package to system operating SuSe 
  when: ( ansible_distribution == 'SLES' or ansible_distribution == 'SLES_SAP' )
  zypper:
    name: '*'
    state: latest 
    update_cache: true
  environment: "{{ proxy_env | default(omit)}}"
