---
 - name: Extend disk in LVM
   hosts: all
   become: free
   vars:
    disks:
     - sdc
     - sdd
    vname: vghanadata1
    lvname: lvhanadata1
   tasks:
    - name: Create partitions
      community.general.parted:
       device: /dev/{{ item }}
       number: 1
       state: present
       part_type: primary
      loop: "{{ disks }}"
