---
- name: Install Package in Linux 
  when: ansible_system == "Linux"
  include_tasks: os_{{ansible_system}}.yml 

- name: Install Package in Windows 
  when: ansible_system == "Windows"
  include_tasks: os_{{ansible_system}}.yml 

- name: Install Package in AIX 
  when: ansible_system == "AIX"
  include_tasks: os_{{ansible_system}}.yml