---
- name: Change Configurations
  lineinfile:
    path: "{{ pathntw }}"
    line: "{{ item }} = 0"
  with_items:
     - net.ipv4.ip_forward
     - net.ipv4.conf.all.send_redirects
     - net.ipv4.conf.default.send_redirects
     - net.ipv4.conf.all.accept_source_route
     - net.ipv4.conf.default.accept_source_route
     - net.ipv6.conf.all.accept_source_route
     - net.ipv6.conf.default.accept_source_route
     - net.ipv4.conf.all.accept_redirects
     - net.ipv4.conf.default.accept_redirects
     - net.ipv6.conf.default.accept_redirects
     - net.ipv4.conf.all.secure_redirects
     - net.ipv4.conf.default.secure_redirects
     - net.ipv6.conf.all.accept_ra
     - net.ipv6.conf.default.accept_ra

- name: Change Configurations
  lineinfile:
    path: "{{ pathntw }}"
    line: "{{ item }} = 1"
  with_items:
     - net.ipv4.conf.all.log_martians
     - net.ipv4.conf.default.log_martians
     - net.ipv4.icmp_echo_ignore_broadcasts
     - net.ipv4.icmp_ignore_bogus_error_responses
     - net.ipv4.conf.all.rp_filter
     - net.ipv4.conf.default.rp_filter
     - net.ipv4.tcp_syncookies

- name: Refresh Sysctl
  shell: 'sysctl -p {{ pathntw }}'
  ignore_errors: true
...
