---
  - hosts: all 
    vars:
      RUTA: "/root/hardening/backup"
      FILE: "/root/hardening/backup/hardening.log"  
    tasks: 

    - name: check the directory in remote server
      stat:
        path: '{{ RUTA }}'
      register: register_ruta

    - name: check the file remote log 
      failed_when: register_ruta.rc == '1'
      stat:
        path: "{{ FILE }}" 
      register: register_file1

    - name: current SHA1 to file1 
      set_fact:
        mf1sha1: "{{ register_file1.stat.checksum }}"

    - name: copy template with remote server 
      template: 
        src: "templates/hardening.log"
        dest: /tmp/hardening.log 

    - name: check the file2
      stat:
        path: "/tmp/hardengin.log"
      register: mysecondfile 

    - name: current SHA1 to file2
      set_fact:
        mf2sha1: '{{ mysecondfile.stat.check }}'

    - name: Compilation Changed 
      debug: 
        msg: "File Compare"
      failed_when: mf2sha1 != mf1sha1
      

