---
- name: Install subsonic for GnuLinux
  hosts: all
  become: true
  vars:
    version: 6.1.6
    package: openjdk-8-jre
  gather_facts: true
  tasks:
    - name: Install packages necesary
      ansible.builtin.package:
        name: "{{ package }}"
        state: present

    - name: Create group subsonic
      ansible.builtin.group:
        name: subsonic
        state: present

    - name: Add user subsonic to the group subsonic
      ansible.builtin.user:
        name: subsonic
        groups: ["subsonic"]
        append: true
        create_home: true
        home: /opt/subsonic
        shell: /bin/bash

    - name: Download the package for the distribution
      when: ansible_os_family == "Debian"
      ansible.builtin.get_url:
        url: https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-{{ version }}.deb
        dest: /tmp
        owner: root
        group: root
        mode: "0600"

    - name: Install package in local compute
      ansible.builtin.apt:
        deb: file=/tmp/subsonic-{{ version }}.deb
        state: present

    - name: Pause to get some sensitive input
      ansible.builtin.pause:
        prompt: "Enter a secret"
        echo: true

    - name: Start and enable Subsonic service
      ansible.builtin.systemd:
        name: subsonic
        state: started
        enabled: true
